stages:
  - build-image
  - deploy
  - restart

variables:
  VUE_APP_BASE_ROUTE: "/"
  VUE_APP_I18N_LOCALE: "fa"
  VUE_APP_I18N_FALLBACK_LOCALE: "en"
  VUE_APP_NAME: "Bourse Panel"
  REF_NAME: $CI_COMMIT_REF_NAME


build-image-General:
  stage: build-image
  tags:
    - SftWre
  script:
    - echo $VUE_APP_BASE_ROUTE
    - docker login -u $user_repository -p $pass_repository https://$repository
    - docker build 
      --build-arg VUE_APP_BASE_ROUTE=$VUE_APP_BASE_ROUTE
      --build-arg VUE_APP_I18N_LOCALE=$VUE_APP_I18N_LOCALE 
      --build-arg VUE_APP_I18N_FALLBACK_LOCALE=$VUE_APP_I18N_FALLBACK_LOCALE 
      --build-arg VUE_APP_Host=$VUE_APP_Host_Dev
      --build-arg REF_NAME=$CI_COMMIT_REF_NAME
      -t $CONTAINER_NAME .
    - docker tag $CONTAINER_NAME  $repository/docker/bourse/$CONTAINER_NAME:$CI_COMMIT_REF_NAME
    - docker push $repository/docker/bourse/$CONTAINER_NAME:$CI_COMMIT_REF_NAME
    - docker logout
  except:
    changes:
      - docker-compose.yml
      - .gitlab-ci.yml

#### Deploy section ####

Deploy-General:
  stage: deploy
  tags:
    - SftWre
  script:
      - docker pull $repository/docker/bourse/$CONTAINER_NAME:$CI_COMMIT_REF_NAME
      - docker-compose -f $CI_COMMIT_REF_NAME up -d
  when : manual
  

#### Restart section ####

Restart-General:
  stage: restart
  tags: 
    - SftWre
  script:
    - docker-compose down
    - docker-compose -f $CI_COMMIT_REF_NAME up -d
  when: manual
